name: CICD for Food Project Frontend

on:
  push:
    branches: [master]
    paths:
      - frontend/ketanStoresFront/**
  pull_request:
    branches: [master]
    paths:
      - frontend/ketanStoresFront/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up node v16
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Log files in pwd
        run: ls -al

      - name: Build image & push to docker hub
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: valmikdocker/ketan_stores
          tags: frontend
          registry: docker.io
          directory: frontend/ketanStoresFront
          dockerfile: frontend/ketanStoresFront/Dockerfile
          buildArgs: VITE_BACKEND_BASE_URL=${{ secrets.VITE_BACKEND_BASE_URL }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

#  deploy:
#    needs: build
#    runs-on: ubuntu-latest
#    if: ${{ success() }} # ! we only want to deploy if the build was successful
#    steps:
#      - name: executing remote ssh commands
#        uses: appleboy/ssh-action@v1.0.0
#        with:
#          host: ${{ secrets.EC2_SSH_HOST }}
#          username: ${{ secrets.EC2_SSH_USERNAME }}
#          password: ${{ secrets.EC2_SSH_PASSWORD }}
#          script: |
#            cd tracker_project
#            docker compose pull
#            docker image ls
#            docker compose up -d
#            docker ps -a